#Spring JPA
## Spring DATASOURCE (DataSourceAutoConfiguration & DataSourceProperties)
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/bioauth_1
    username: accmanager
    password: accmanager
  jpa:
    properties:
      dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: update
security:
  oauth2:
    resource:
      jwt:
        key-value: bioauthtyping
